export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_USERS = "GET_USERS";
export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const CLEAR_USERS = "CLEAR_USERS";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

//ERRORS TYPES
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING = "LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//Body systems
export const GET_BODY_SYSTEMS = "GET_BODY_SYSTEMS";
export const ADD_BODY_SYSTEM = "ADD_BODY_SYSTEM";
export const EDIT_BODY_SYSTEM = "EDIT_BODY_SYSTEM";
export const DELETE_BODY_SYSTEM = "DELETE_BODY_SYSTEM";

//Drug classes
export const GET_DRUG_CLASSES = "GET_DRUG_CLASSES";
export const ADD_DRUG_CLASS = "ADD_DRUG_CLASS";
export const EDIT_DRUG_CLASS = "EDIT_DRUG_CLASS";
export const DELETE_DRUG_CLASS = "DELETE_DRUG_CLASS";

//Snackbar actions
export const SNACKBAR_CLEAR = "SNACKBAR_CLEAR";
export const SNACKBAR_SUCCESS = "SNACKBAR_SUCCESS";

//Distributor actions
export const GET_DISTRIBUTORS = "GET_DISTRIBUTORS";
export const ADD_DISTRIBUTOR = "ADD_DISTRIBUTOR";
export const EDIT_DISTRIBUTOR = "EDIT_DISTRIBUTOR";
export const DELETE_DISTRIBUTOR = "DELETE_DISTRIBUTOR";

//Posology actions
export const GET_POSOLOGIES = "GET_POSOLOGIES";
export const ADD_POSOLOGY = "ADD_POSOLOGY";
export const EDIT_POSOLOGY = "EDIT_POSOLOGY";
export const DELETE_POSOLOGY = "DELETE_POSOLOGY";

//Frequency actions
export const GET_FREQUENCIES = "GET_FREQUENCIES";
export const ADD_FREQUENCY = "ADD_FREQUENCY";
export const EDIT_FREQUENCY = "EDIT_FREQUENCY";
export const DELETE_FREQUENCY = "DELETE_FREQUENCY";

//Instructions actions
export const GET_INSTRUCTIONS = "GET_INSTRUCTIONS";
export const ADD_INSTRUCTION = "ADD_INSTRUCTION";
export const EDIT_INSTRUCTION = "EDIT_INSTRUCTION";
export const DELETE_INSTRUCTION = "DELETE_INSTRUCTION";

//Drug Sub Classes actions
export const GET_DRUG_SUB_CLASSES = "GET_DRUG_SUB_CLASSES";
export const ADD_DRUG_SUB_CLASS = "ADD_DRUG_SUB_CLASS";
export const EDIT_DRUG_SUB_CLASS = "EDIT_DRUG_SUB_CLASS";
export const DELETE_DRUG_SUB_CLASS = "DELETE_DRUG_SUB_CLASS";

//Formulations actions
export const GET_FORMULATIONS = "GET_FORMULATIONS";
export const ADD_FORMULATION = "ADD_FORMULATION";
export const EDIT_FORMULATION = "EDIT_FORMULATION";
export const DELETE_FORMULATION = "DELETE_FORMULATION";

//Generics actions
export const GET_GENERICS = "GET_GENERICS";
export const ADD_GENERIC = "ADD_GENERIC";
export const EDIT_GENERIC = "EDIT_GENERIC";
export const DELETE_GENERIC = "DELETE_GENERIC";

//Preparations actions
export const GET_PREPARATIONS = "GET_PREPARATIONS";
export const ADD_PREPARATION = "ADD_PREPARATION";
export const EDIT_PREPARATION = "EDIT_PREPARATION";
export const DELETE_PREPARATION = "DELETE_PREPARATION";

//Manufacturer actions
export const GET_MANUFACTURERS = "GET_MANUFACTURERS";
export const ADD_MANUFACTURER = "ADD_MANUFACTURER";
export const EDIT_MANUFACTURER = "EDIT_MANUFACTURER";
export const DELETE_MANUFACTURER = "DELETE_MANUFACTURER";

//Product actions
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
