# Generated by Django 3.1.1 on 2020-11-22 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entities.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle', models.CharField(choices=[('MotorCycle', 'Motor Cycle'), ('SaloonCar', 'Saloon Car')], max_length=30)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('licence', models.FileField(upload_to=entities.models.courier_licence_upload_to)),
                ('permit_number', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='users.facility')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cadre', models.CharField(choices=[('PharmTech', 'Pharmaceutical Technologist'), ('Pharmacist', 'Pharmacist')], max_length=30)),
                ('board_number', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate', models.FileField(upload_to=entities.models.certificate_upload_to)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist', to='users.facility')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salutation', models.CharField(blank=True, choices=[('Dr', 'Doctor'), ('Mr', 'Mr'), ('Prof.', 'Professor')], max_length=30, null=True)),
                ('cadre', models.CharField(choices=[('ClinicalOfficer', 'Clinical Officer'), ('Doctor', 'Doctor')], max_length=30)),
                ('board_number', models.CharField(max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate', models.FileField(upload_to=entities.models.certificate_upload_to)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prescriber', to='users.facility')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescriber_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriberPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=entities.models.prescriber_photo_upload_to)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prescriberphoto', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_certificate', to='entities.prescriber')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacistPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=entities.models.pharmacist_photo_upload_to)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacistphoto', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_certificate', to='entities.pharmacist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityPrescriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superintendent', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='facilityprescriber', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_prescriber_owner', to=settings.AUTH_USER_MODEL)),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_prescriber', to='entities.prescriber')),
            ],
            options={
                'db_table': 'prescribers_for_facility',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='FacilityPharmacist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superintendent', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='facilitypharmacist', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_pharmacist_owner', to=settings.AUTH_USER_MODEL)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_pharmacist', to='entities.pharmacist')),
            ],
            options={
                'db_table': 'pharmacists_for_facility',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='FacilityCourier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_courier', to='entities.courier')),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='facilitycourier', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_courier_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'couriers_for_facility',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CourierPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=entities.models.courier_photo_upload_to)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_certificate', to='entities.courier')),
                ('facility', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='courierphoto', to='users.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
